Platoon: Follower App
BlueAndi/RadonUlzer pull request #81
Opened 2024-01-30 08:25 UTC by gabryelreyes

Adapted AppRemoteControl to be used as counterpart of the Platoon Follower application of DCS.

- In ConvoyLeader: Do not go into ErrorState once the run is finished. This would stop all vehicles instantly and not allow vehicles to finish the track.

2024-01-30 18:44 UTC, BlueAndi requested changes

2024-01-30 18:44 UTC, BlueAndi commented on lib/APPRemoteControl/App.h
> +    void handleRemoteCommands(const Command& cmd);
According to the comment, it handles several commands. But according to the parameters, it handles just one command at once.

2024-01-30 18:44 UTC, BlueAndi commented on lib/APPRemoteControl/LineSensorsCalibrationState.cpp
> +        // sm.setState(&RemoteCtrlState::getInstance());
State change missing? Its not clear for me what should happen here.

2024-01-30 20:23 UTC, BlueAndi approved these changes

2024-01-30 20:23 UTC, merged

2024-01-31 08:54 UTC, nhjschulz reviewed
a few comments to consider

2024-01-31 08:54 UTC, nhjschulz commented on lib/APPRemoteControl/App.cpp
> +    if ((true == m_reportTimer.isTimeout()) && (true == m_smpServer.isSynced()))
can you extract the block depenended on m_smpServer.isSynced() into a sub-function ? This function is getting big.

2024-01-31 08:54 UTC, nhjschulz commented on lib/APPRemoteControl/App.cpp
> +        rsp.responseId = SMPChannelPayload::RSP_ID_ERROR;
not known/relevant is not the same as ERROR typically.
Consider a "UNKNOWN" return to help caller to handle ERROR and not implemented/relevant differently.

2024-01-31 08:54 UTC, nhjschulz commented on lib/APPRemoteControl/App.cpp
> +    (void)m_smpServer.sendData(m_serialMuxProtChannelIdLineSensors, &payload, sizeof(payload));
Line 301 is risky as LineSensorData buffer and lineSensors.getNumLineSensors() need to argree on size to avoid a buffer overflow.  Not sure how to fix as the dynamics of the API make it hard for LineSensorData to be big enough.

2024-01-31 08:54 UTC, nhjschulz commented on lib/APPRemoteControl/App.cpp
>      }
I suggest a log message in the else case as this if may fail during development cycles and a log would help debugging.

2024-01-31 08:54 UTC, nhjschulz commented on lib/APPRemoteControl/SerialMuxChannels.h
> +    uint16_t lineSensorData[5U]; /**< Line sensor data [digits] normalized to max 1000 digits. */
This 5 is asking for trouble. See my former comment on filling this data.

2024-01-31 08:54 UTC, nhjschulz commented on lib/APPRemoteControl/StartupState.h
> +    static const uint32_t APP_NAME_DURATION = 2000U;
a good habbit is to tell in what physical unit the value is i.e.
APP_NAME_DURATION**_MS**  = 2000U;